SNP_SHARED_MAKEFILE := $(if $(SNP_SHARED_MAKEFILE),$(SNP_SHARED_MAKEFILE),"~/snp/shared.mk")

TARGET     := bin/sorting
# MODULES    := src/sorting.c
 SOURCES    := src/main.c
# TSTSOURCES := tests/tests.c $(MODULES)

include $(SNP_SHARED_MAKEFILE)
